from django.urls import path

from metro_app import views

urlpatterns=[
    path('',views.home,name='home'),
    path('admin_home',views.admin_home,name='admin_home'),
    path('login_view',views.login_view,name='login_view'),
    path('logout_view',views.logout_view,name='logout_view'),
    path('register',views.register,name='register'),
    path('trainer_home',views.trainer_home,name='trainer_home'),
    path('trainer_register',views.trainer_register,name='trainer_register'),
    path('trainer_view',views.trainer_view,name='trainer_view'),
    path('trainer_delete/<int:id>',views.trainer_delete,name='trainer_delete'),
    path('physician_register',views.physician_register,name='physician_register'),
    path('physician_view',views.physician_view,name='physician_view'),
    path('physician_delete/<int:id>',views.physician_delete,name='physician_delete'),
    path('add_equipments',views.add_equipments,name='add_equipments'),
    path('equipments_view', views.equipments_view, name='equipments_view'),
    path('equipments_delete/<int:id>', views.equipments_delete, name='equipments_delete'),
    path('user_home',views.user_home,name='user_home'),
    path('userequipments_view',views.userequipments_view,name='userequipments_view'),
    path('usertrainer_view',views.usertrainer_view,name='usertrainer_view'),
    path('userphysician_view',views.userphysician_view,name='userphysician_view'),
    path('customer_register',views.customer_register,name='customer_register'),
    path('add_batch',views.add_batch,name='add_batch'),
    path('batch_view',views.batch_view,name='batch_view'),
    path('batch_delete/<int:id>', views.batch_delete, name='batch_delete'),
    path('batch_update/<int:id>',views.batch_update,name='batch_update'),
    path('add_complaint',views.add_complaint,name='add_complaint'),
    path('complaint_view',views.complaint_view,name='complaint_view'),
    path('complaint_admview', views.complaint_admview, name='complaint_admview'),
    path('add_reply/<int:id>', views.add_reply, name='add_reply'),
    path('add_dietplan',views.add_dietplan,name='add_dietplan'),
    path('dietplan_view',views.dietplan_view,name='dietplan_view'),
    path('dietplanuser_view',views.dietplanuser_view,name='dietplanuser_view'),
    path('customer_view',views.customer_view,name='customer_view'),
    path('customer_delete/<int:id>', views.customer_delete, name='customer_delete'),
    path('add_attendance',views.add_attendance,name='add_attendance'),
    path('mark_attendance/<int:id>',views.mark_attendance,name='mark_attendance'),
    path('view_attendance',views.view_attendance,name='view_attendance'),
    path('day_attendance/<date>',views.day_attendance,name='day_attendance'),
    path('add_health',views.add_health,name='add_health'),
    path('health_view',views.health_view,name='health_view'),
    path('trainer_custview',views.trainer_custview,name='trainer_custview'),
    path('add_notification',views.add_notification,name='add_notification'),
    path('add_payment',views.add_payment,name='add_payment'),
    path('payment_view',views.payment_view,name='payment_view'),
    path('view_notification',views.view_notification,name='view_notification'),
    path('userpayment_view',views.userpayment_view,name='userpayment_view'),
    path('notification_view',views.notification_view,name='notification_view'),
    path('profile_view',views.profile_view,name='profile_view'),
    path('add_card/<int:id>',views.add_card,name='add_card'),
    path('cardpay_view',views.cardpay_view,name='cardpay_view')



]